pipeline {
    agent any

    environment {
        // Change build server IP acccording to your AWS EC2 Build server Private Ip
        BUILD_SERVER_IP = '13.204.84.24'
    }

    stages {
        stage('Cleanup and Clone Repository') {
            steps {
                script {
                    // Remove existing Day6 directory and clone the latest repo
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'sudo rm -rf /home/ubuntu/Day* && git clone https://github.com/krishna1369/Docker_tagging_with_gitcommitid.git /home/ubuntu/Docker_tagging_with_gitcommitid'"
                }
            }
        }

        stage('Build Docker images on Build Server') {
            steps {
                script {
                    // Execute Ansible playbook on Build Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/Docker_tagging_with_gitcommitid/Ansible/build.yaml'"
                }
            }
        }

        stage('Deploy Script on Deploy Server') {
            steps {
                script {
                    // Execute deployment playbook on Deploy Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/Docker_tagging_with_gitcommitid/Ansible/deploy.yaml'"
                }
            }
        }
    }
}
